# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=140)),
                ('user_location', models.TextField()),
                ('user_location_latitude', models.FloatField()),
                ('user_location_longitude', models.FloatField()),
                ('user_lang', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('import_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
