# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='import_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_lang',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_location_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_location_longitude',
            field=models.FloatField(null=True),
        ),
    ]
