# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0002_auto_20160430_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_lang',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_screen_name',
            field=models.TextField(null=True),
        ),
    ]
