# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0003_auto_20160511_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField()),
                ('run_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='import_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
