# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0004_auto_20160515_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet_original',
            field=models.BooleanField(default=False),
        ),
    ]
